{
	"version": 1574842396,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/gatotkaca-sheet0.png",
		"images/gatotkaca-sheet1.png",
		"images/gatotkaca-sheet2.png",
		"images/stone-sheet0.png",
		"images/stone-sheet1.png",
		"images/particles.png",
		"images/mountain_risk-sheet0.png",
		"images/mountain_risk2-sheet0.png",
		"images/food-sheet0.png",
		"images/food-sheet1.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/particles2.png",
		"images/particles3.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/stone2-sheet0.png",
		"images/particles46.png",
		"images/particles47.png",
		"images/title_page-sheet0.png",
		"images/load-sheet0.png",
		"images/hud_score_point-sheet0.png",
		"images/resume-sheet0.png",
		"images/pause-sheet0.png",
		"images/dead-sheet0.png",
		"images/enemy_hud-sheet0.png",
		"images/bossy_bar-sheet0.png",
		"images/particles6.png",
		"images/save-sheet0.png",
		"images/big_boss2-sheet0.png",
		"images/big_boss2-sheet1.png",
		"images/big_boss2-sheet2.png",
		"images/tiledbackground.png",
		"images/close-sheet0.png",
		"images/mask1-sheet0.png",
		"images/spot1-sheet0.png",
		"images/spot1-sheet1.png",
		"images/caster1-sheet0.png",
		"images/spot2-sheet0.png",
		"images/particles8.png",
		"images/sprite5-sheet0.png",
		"images/sprite5-sheet1.png",
		"images/sprite12-sheet0.png",
		"images/sprite12-sheet1.png",
		"images/sprite15-sheet0.png",
		"images/close2-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/title_page2-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite20-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/sprite24-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sprite26-sheet0.png",
		"images/settings-sheet0.png",
		"images/sprite28-sheet0.png",
		"images/sprite33-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite47-sheet0.png",
		"images/splash.png",
		"images/raindrop-sheet0.png",
		"images/cast-sheet0.png",
		"images/mati-sheet0.png",
		"images/mati-sheet1.png",
		"images/playerbox-sheet0.png",
		"images/gmover-sheet0.png",
		"images/particles48.png",
		"images/hudheart_full-sheet0.png",
		"images/efekhealt.png",
		"images/gems-sheet0.png",
		"images/efekgems.png",
		"images/bonus-sheet0.png",
		"images/bonus-sheet1.png",
		"images/particles9.png",
		"media/explosion 2.m4a",
		"media/explosion 2.ogg",
		"media/cancel - 5.m4a",
		"media/cancel - 5.ogg",
		"media/explosion 4.m4a",
		"media/explosion 4.ogg",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/tribal jungle music - aztec jungle.m4a",
		"media/tribal jungle music - aztec jungle.ogg",
		"media/havana.m4a",
		"media/boss.m4a",
		"media/boss.ogg",
		"media/dragon sound effects.m4a",
		"media/dragon sound effects.ogg",
		"media/oops1.ogg",
		"media/oops1.m4a",
		"media/beathunterz -- gamelan instrumental hiphop beatz -.m4a",
		"media/beathunterz -- gamelan instrumental hiphop beatz -.ogg",
		"media/hip hop rap beat.m4a",
		"media/hip hop rap beat.ogg",
		"media/kalah.m4a",
		"media/kalah.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"three.min.js",
		"OBJLoader.js",
		"Q3D.collisionSystem.js",
		"Q3D.migrate.js",
		"Q3D.commonACE.js",
		"Q3D.qfxLoader.js",
		"WebGLDeferredRenderer.js",
		"ShaderDeferred.js",
		"CopyShader.js",
		"FXAAShader.js",
		"EffectComposer.js",
		"RenderPass.js",
		"ShaderPass.js",
		"MaskPass.js",
		"Q3D.SkinnedMesh.js",
		"penumbra.png"
	]
}